#!/bin/bash

time=0
while true; do
  newtime=$(find ./src -regex "[^#]*\.rs" -exec stat -f "%m" \{} \; | sort -n -r | head -1)
  if [ "$newtime" -gt "$time" ]; then
    clear
    cargo build
  fi

  time=$newtime;
  sleep 1
done
